name: Coding Standards

on: [fork, pull_request, push]

jobs:
  coding-standards:
    name: Coding Standards

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: intl
          php-version: ${{ matrix.php-version }}

      - name: Determine composer cache directory
        id: determine-composer-cache-directory
        run: echo "directory=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies installed with composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install dependencies with composer
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Run squizlabs/php_codesniffer
        run: vendor/bin/phpcs --standard=PSR2 src -n
